### ISSUE TITLE
Seleccionar en el video los cuatro puntos

### ISSUE THREAD

**Issue by ivanClass** [11crom11/Perspective#4]
Creación de los cuatro puntos y asignación en el vídeo.
Investigar la manera en cómo colocarlos y mostrarlos.

**Comment by 11crom11** [comment]
- Creado un pequeño index donde observar el funcionamiento.
- Incluidas las librerias Konva.js y Current.Thread.js.
- Imagen de una pizarra de fondo para probar a mover los puntos en las esquinas. Al mover un punto y soltarlo, aparece a modo de depuración un alert indicando las coordenadas del punto dentro de la imagen.
- Debido a que el manejador de eventos por defecto de los puntos está funcionando cada vez que se mueve alguno, para poder mover las líneas que unen los puntos de manera dinámica ha sido necesario la utilización de Threads para que a medida que se vayan moviendo los puntos, las líneas se vayan dibujando con las nuevas coordenadas de lo puntos.
- Las coordenadas de los puntos se almacenan en una estructura para su posterior consulta.
